---
- name: Retrieve windows updates
  hosts: all
  tasks:
    - name: Install windows updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: yes